version: '2'

services:
    dynamodb:
        image: dwmkerr/dynamodb
        tty: true
        ports:
            - "8000:8000"

    # basenode:
    #     build: ./base
    #     stdin_open: true
    #     tty: true
    masternode:
        build: ./master
        stdin_open: true
        tty: true
        ports:
            - "7557:7557"
            - "2910:2910"
        expose:
            - 7557
            - 2910
        environment:
            CHAINNAME: registryv3
            NETWORK_PORT: 7557
            RPC_PORT: 2910
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|false
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|false
            PARAM_ALLOW_P2SH_OUTPUTS: allow-p2sh-outputs|true
            PARAM_ALLOW_MULTISIG_OUTPUTS: allow-multisig-outputs|true
    slavenode:
        build: ./node
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 2910
        environment:
            CHAINNAME: registryv3
            NETWORK_PORT: 7557
            RPC_PORT: 2910
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
    explorernode:
        build: ./explorer
        stdin_open: true
        tty: true
        ports:
            - "2750:2750"
        expose:
            - 2750
            - 7557
            - 2910
        environment:
            CHAINNAME: registryv3
            NETWORK_PORT: 7557
            RPC_PORT: 2910
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
